import { ModelData } from "@/components/Leaderboard";

export const scoresData: ModelData[] = [
    {
        model: "o3-2025-04-16", // Or a more current o3 model
        pass1_build: 35,
        pass1_test: 19,
        compiler_repair_build: 68,
        compiler_repair_test: 31,
        test_repair_build: 68,
        test_repair_test: 31,
    }, 
    {
        model: "o1-preview-2024-09-12", // Or a more current o1 model
        pass1_build: 32,
        pass1_test: 15,
        compiler_repair_build: 69,
        compiler_repair_test: 28,
        test_repair_build: 54,
        test_repair_test: 37,
    },
    {
        model: "claude-3.7-sonnet-20250219",
        pass1_build: 26,
        pass1_test: 13,
        compiler_repair_build: 54,
        compiler_repair_test: 23,
        test_repair_build: 49,
        test_repair_test: 32,
    },
    {
        model: "claude-3.5-sonnet-20240620",
        pass1_build: 26,
        pass1_test: 11,
        compiler_repair_build: 49,
        compiler_repair_test: 21,
        test_repair_build: 38,
        test_repair_test: 24,
    },
    {
        model: "o1-mini-2024-09-12",
        pass1_build: 19,
        pass1_test: 9,
        compiler_repair_build: 47,
        compiler_repair_test: 16,
        test_repair_build: 27,
        test_repair_test: 21,
    },
    {
        model: "gpt-4o",
        pass1_build: 18,
        pass1_test: 7,
        compiler_repair_build: 52,
        compiler_repair_test: 18,
        test_repair_build: 42,
        test_repair_test: 22,
    },
    {
        model: "gemini-1.5-pro",
        pass1_build: 11,
        pass1_test: 3,
        compiler_repair_build: 35,
        compiler_repair_test: 11,
        test_repair_build: 30,
        test_repair_test: 14,
    },
    {
        model: "arcee-ai/Virtuoso-Medium-v2", // Example repository name
        pass1_build: 2,
        pass1_test: 2,
        compiler_repair_build: 21,
        compiler_repair_test: 6,
        test_repair_build: 10,
        test_repair_test: 6,
    },
    {
        model: "Qwen/QwQ-32B-Preview",
        pass1_build: 1,
        pass1_test: 0,
        compiler_repair_build: 1,
        compiler_repair_test: 0,
        test_repair_build: 1,
        test_repair_test: 0,
    },
    {
        model: "Adapted SWE-agent (claude-3-7-sonnet-20250219)",
        pass1_build: 41,
        pass1_test: 32,
        compiler_repair_build: "–",
        compiler_repair_test: "–",
        test_repair_build: "–",
        test_repair_test: "–",
        is_adapted: true,
    },
];